window.vocabularyData = [
  {
    id: 1,
    category: "Greetings",
    korean: "안녕하세요",
    romanization: "annyeonghaseyo",
    en: "Hello",
    ja: "こんにちは",
    zh: "你好",
    es: "Hola",
    example_ko: "안녕하세요, 만나서 반가워요.",
    example_en: "Hello, nice to meet you.",
    example_ja: "こんにちは、お会いできて嬉しいです。",
    example_zh: "你好，很高兴见到你。",
    example_es: "Hola, encantado de conocerte."
  },
  {
    id: 2,
    category: "Greetings",
    korean: "감사합니다",
    romanization: "gamsahamnida",
    en: "Thank you",
    ja: "ありがとうございます",
    zh: "谢谢",
    es: "Gracias",
    example_ko: "도와주셔서 감사합니다.",
    example_en: "Thank you for your help.",
    example_ja: "助けてくれてありがとうございます。",
    example_zh: "谢谢你的帮助。",
    example_es: "Gracias por su ayuda."
  },
  {
    id: 3,
    category: "Greetings",
    korean: "죄송합니다",
    romanization: "joesonghamnida",
    en: "I'm sorry",
    ja: "すみません / ごめんなさい",
    zh: "对不起",
    es: "Lo siento",
    example_ko: "늦어서 죄송합니다.",
    example_en: "I'm sorry for being late.",
    example_ja: "遅れてすみません。",
    example_zh: "对不起，我迟到了。",
    example_es: "Siento llegar tarde."
  },
  {
    id: 4,
    category: "Greetings",
    korean: "네",
    romanization: "ne",
    en: "Yes",
    ja: "はい",
    zh: "是",
    es: "Sí",
    example_ko: "네, 알겠습니다.",
    example_en: "Yes, I understand.",
    example_ja: "はい、わかりました。",
    example_zh: "是的，我知道了。",
    example_es: "Sí, entiendo."
  },
  {
    id: 5,
    category: "Greetings",
    korean: "아니요",
    romanization: "aniyo",
    en: "No",
    ja: "いいえ",
    zh: "不是",
    es: "No",
    example_ko: "아니요, 괜찮습니다.",
    example_en: "No, it's okay.",
    example_ja: "いいえ、大丈夫です。",
    example_zh: "不，没关系。",
    example_es: "No, está bien."
  },
  {
    id: 6,
    category: "Food",
    korean: "물",
    romanization: "mul",
    en: "Water",
    ja: "水",
    zh: "水",
    es: "Agua",
    example_ko: "물 좀 주세요.",
    example_en: "Please give me some water.",
    example_ja: "お水をください。",
    example_zh: "请给我点水。",
    example_es: "Por favor, dame un poco de agua."
  },
  {
    id: 7,
    category: "Food",
    korean: "밥",
    romanization: "bap",
    en: "Rice / Meal",
    ja: "ご飯",
    zh: "米饭 / 饭",
    es: "Arroz / Comida",
    example_ko: "밥 먹었어요?",
    example_en: "Did you eat?",
    example_ja: "ご飯食べましたか？",
    example_zh: "你吃饭了吗？",
    example_es: "¿Has comido?"
  },
  {
    id: 8,
    category: "Food",
    korean: "김치",
    romanization: "kimchi",
    en: "Kimchi",
    ja: "キムチ",
    zh: "泡菜",
    es: "Kimchi",
    example_ko: "한국 사람들은 김치를 좋아해요.",
    example_en: "Korean people like kimchi.",
    example_ja: "韓国人はキムチが好きです。",
    example_zh: "韩国人喜欢泡菜。",
    example_es: "A los coreanos les gusta el kimchi."
  },
  {
    id: 9,
    category: "Food",
    korean: "불고기",
    romanization: "bulgogi",
    en: "Bulgogi (Marinated Beef)",
    ja: "プルコギ",
    zh: "烤肉",
    es: "Bulgogi",
    example_ko: "불고기는 달콤하고 맛있어요.",
    example_en: "Bulgogi is sweet and delicious.",
    example_ja: "プルコギは甘くて美味しいです。",
    example_zh: "烤肉又甜又好吃。",
    example_es: "El bulgogi es dulce y delicioso."
  },
  {
    id: 10,
    category: "Food",
    korean: "비빔밥",
    romanization: "bibimbap",
    en: "Bibimbap",
    ja: "ビビンバ",
    zh: "拌饭",
    es: "Bibimbap",
    example_ko: "점심으로 비빔밥을 먹었어요.",
    example_en: "I ate bibimbap for lunch.",
    example_ja: "お昼にビビンバを食べました。",
    example_zh: "我午饭吃了拌饭。",
    example_es: "Comí bibimbap para el almuerzo."
  },
  {
    id: 11,
    category: "Verbs",
    korean: "가다",
    romanization: "gada",
    en: "To go",
    ja: "行く",
    zh: "去",
    es: "Ir",
    example_ko: "학교에 가요.",
    example_en: "I go to school.",
    example_ja: "学校に行きます。",
    example_zh: "去学校。",
    example_es: "Voy a la escuela."
  },
  {
    id: 12,
    category: "Verbs",
    korean: "오다",
    romanization: "oda",
    en: "To come",
    ja: "来る",
    zh: "来",
    es: "Venir",
    example_ko: "빨리 오세요.",
    example_en: "Please come quickly.",
    example_ja: "早く来てください。",
    example_zh: "请快点来。",
    example_es: "Por favor, ven rápido."
  },
  {
    id: 13,
    category: "Verbs",
    korean: "먹다",
    romanization: "meokda",
    en: "To eat",
    ja: "食べる",
    zh: "吃",
    es: "Comer",
    example_ko: "사과를 먹어요.",
    example_en: "I eat an apple.",
    example_ja: "りんごを食べます。",
    example_zh: "吃苹果。",
    example_es: "Como una manzana."
  },
  {
    id: 14,
    category: "Verbs",
    korean: "마시다",
    romanization: "masida",
    en: "To drink",
    ja: "飲む",
    zh: "喝",
    es: "Beber",
    example_ko: "커피를 마셔요.",
    example_en: "I drink coffee.",
    example_ja: "コーヒーを飲みます。",
    example_zh: "喝咖啡。",
    example_es: "Bebo café."
  },
  {
    id: 15,
    category: "Verbs",
    korean: "자다",
    romanization: "jada",
    en: "To sleep",
    ja: "寝る",
    zh: "睡",
    es: "Dormir",
    example_ko: "일찍 자요.",
    example_en: "I sleep early.",
    example_ja: "早く寝ます。",
    example_zh: "早点睡。",
    example_es: "Duermo temprano."
  },
  {
    id: 16,
    category: "Adjectives",
    korean: "크다",
    romanization: "keuda",
    en: "To be big",
    ja: "大きい",
    zh: "大",
    es: "Grande",
    example_ko: "집이 정말 커요.",
    example_en: "The house is really big.",
    example_ja: "家が本当に大きいです。",
    example_zh: "房子真的很大。",
    example_es: "La casa es muy grande."
  },
  {
    id: 17,
    category: "Adjectives",
    korean: "작다",
    romanization: "jakda",
    en: "To be small",
    ja: "小さい",
    zh: "小",
    es: "Pequeño",
    example_ko: "강아지가 작고 귀여워요.",
    example_en: "The puppy is small and cute.",
    example_ja: "子犬が小さくて可愛いです。",
    example_zh: "小狗又小又可爱。",
    example_es: "El cachorro es pequeño y lindo."
  },
  {
    id: 18,
    category: "Adjectives",
    korean: "좋다",
    romanization: "jota",
    en: "To be good",
    ja: "良い",
    zh: "好",
    es: "Bueno",
    example_ko: "날씨가 정말 좋아요.",
    example_en: "The weather is really good.",
    example_ja: "天気が本当に良いです。",
    example_zh: "天气真的很好。",
    example_es: "El tiempo es realmente bueno."
  },
  {
    id: 19,
    category: "Adjectives",
    korean: "나쁘다",
    romanization: "nappeuda",
    en: "To be bad",
    ja: "悪い",
    zh: "坏",
    es: "Malo",
    example_ko: "공기가 나빠요.",
    example_en: "The air quality is bad.",
    example_ja: "空気が悪いです。",
    example_zh: "空气不好。",
    example_es: "La calidad del aire es mala."
  },
  {
    id: 20,
    category: "Adjectives",
    korean: "비싸다",
    romanization: "bissada",
    en: "To be expensive",
    ja: "高い",
    zh: "贵",
    es: "Caro",
    example_ko: "이 가방은 너무 비싸요.",
    example_en: "This bag is too expensive.",
    example_ja: "このバッグは高すぎます。",
    example_zh: "这个包太贵了。",
    example_es: "Este bolso es demasiado caro."
  },
  {
    id: 21,
    category: "Travel",
    korean: "공항",
    romanization: "gonghang",
    en: "Airport",
    ja: "空港",
    zh: "机场",
    es: "Aeropuerto",
    example_ko: "인천 공항에 도착했어요.",
    example_en: "I arrived at Incheon Airport.",
    example_ja: "仁川空港に到着しました。",
    example_zh: "我到了仁川机场。",
    example_es: "Llegué al aeropuerto de Incheon."
  },
  {
    id: 22,
    category: "Travel",
    korean: "여권",
    romanization: "yeogwon",
    en: "Passport",
    ja: "パスポート",
    zh: "护照",
    es: "Pasaporte",
    example_ko: "여권을 잃어버리지 마세요.",
    example_en: "Don't lose your passport.",
    example_ja: "パスポートをなくさないでください。",
    example_zh: "不要弄丢护照。",
    example_es: "No pierdas tu pasaporte."
  },
  {
    id: 23,
    category: "Travel",
    korean: "비행기",
    romanization: "bihaenggi",
    en: "Airplane",
    ja: "飛行機",
    zh: "飞机",
    es: "Avión",
    example_ko: "비행기표를 예약했어요.",
    example_en: "I booked an airplane ticket.",
    example_ja: "飛行機のチケットを予約しました。",
    example_zh: "我预订了机票。",
    example_es: "Reservé un billete de avión."
  },
  {
    id: 24,
    category: "Travel",
    korean: "호텔",
    romanization: "hotel",
    en: "Hotel",
    ja: "ホテル",
    zh: "酒店",
    es: "Hotel",
    example_ko: "호텔이 깨끗해요.",
    example_en: "The hotel is clean.",
    example_ja: "ホテルが綺麗です。",
    example_zh: "酒店很干净。",
    example_es: "El hotel está limpio."
  },
  {
    id: 25,
    category: "Travel",
    korean: "지도",
    romanization: "jido",
    en: "Map",
    ja: "地図",
    zh: "地图",
    es: "Mapa",
    example_ko: "지도를 보고 길을 찾아요.",
    example_en: "I look at the map to find the way.",
    example_ja: "地図を見て道を探します。",
    example_zh: "看地图找路。",
    example_es: "Miro el mapa para encontrar el camino."
  },
  {
    id: 26,
    category: "People",
    korean: "친구",
    romanization: "chingu",
    en: "Friend",
    ja: "友達",
    zh: "朋友",
    es: "Amigo",
    example_ko: "제 친구는 친절해요.",
    example_en: "My friend is kind.",
    example_ja: "私の友達は親切です。",
    example_zh: "我的朋友很亲切。",
    example_es: "Mi amigo es amable."
  },
  {
    id: 27,
    category: "People",
    korean: "가족",
    romanization: "gajok",
    en: "Family",
    ja: "家族",
    zh: "家族",
    es: "Familia",
    example_ko: "가족과 함께 여행을 가요.",
    example_en: "I go on a trip with my family.",
    example_ja: "家族と一緒に旅行に行きます。",
    example_zh: "和家人一起去旅行。",
    example_es: "Voy de viaje con mi familia."
  },
  {
    id: 28,
    category: "People",
    korean: "아버지",
    romanization: "abeoji",
    en: "Father",
    ja: "お父さん",
    zh: "父亲",
    es: "Padre",
    example_ko: "아버지는 회사원이에요.",
    example_en: "My father is an office worker.",
    example_ja: "父は会社員です。",
    example_zh: "我父亲是上班族。",
    example_es: "Mi padre es oficinista."
  },
  {
    id: 29,
    category: "People",
    korean: "어머니",
    romanization: "eomeoni",
    en: "Mother",
    ja: "お母さん",
    zh: "母亲",
    es: "Madre",
    example_ko: "어머니는 요리를 잘하세요.",
    example_en: "My mother is good at cooking.",
    example_ja: "母は料理が上手です。",
    example_zh: "我母亲擅长做饭。",
    example_es: "Mi madre cocina bien."
  },
  {
    id: 30,
    category: "People",
    korean: "동생",
    romanization: "dongsaeng",
    en: "Younger sibling",
    ja: "妹 / 弟",
    zh: "弟弟 / 妹妹",
    es: "Hermano/a menor",
    example_ko: "동생이 숙제를 해요.",
    example_en: "My younger sibling is doing homework.",
    example_ja: "弟（妹）が宿題をしています。",
    example_zh: "弟弟（妹妹）在做作业。",
    example_es: "Mi hermano menor está haciendo la tarea."
  },
  {
    id: 31,
    category: "Time",
    korean: "오늘",
    romanization: "oneul",
    en: "Today",
    ja: "今日",
    zh: "今天",
    es: "Hoy",
    example_ko: "오늘은 날씨가 맑아요.",
    example_en: "Today the weather is clear.",
    example_ja: "今日は天気が晴れです。",
    example_zh: "今天天气晴朗。",
    example_es: "Hoy el tiempo está despejado."
  },
  {
    id: 32,
    category: "Time",
    korean: "내일",
    romanization: "naeil",
    en: "Tomorrow",
    ja: "明日",
    zh: "明天",
    es: "Mañana",
    example_ko: "내일 만나요.",
    example_en: "See you tomorrow.",
    example_ja: "明日会いましょう。",
    example_zh: "明天见。",
    example_es: "Nos vemos mañana."
  },
  {
    id: 33,
    category: "Time",
    korean: "어제",
    romanization: "eoje",
    en: "Yesterday",
    ja: "昨日",
    zh: "昨天",
    es: "Ayer",
    example_ko: "어제는 바빴어요.",
    example_en: "I was busy yesterday.",
    example_ja: "昨日は忙しかったです。",
    example_zh: "昨天很忙。",
    example_es: "Ayer estuve ocupado."
  },
  {
    id: 34,
    category: "Time",
    korean: "지금",
    romanization: "jigeum",
    en: "Now",
    ja: "今",
    zh: "现在",
    es: "Ahora",
    example_ko: "지금 몇 시예요?",
    example_en: "What time is it now?",
    example_ja: "今、何時ですか？",
    example_zh: "现在几点？",
    example_es: "¿Qué hora es ahora?"
  },
  {
    id: 35,
    category: "Time",
    korean: "시간",
    romanization: "sigan",
    en: "Time / Hour",
    ja: "時間",
    zh: "时间",
    es: "Tiempo / Hora",
    example_ko: "시간이 없어요.",
    example_en: "I don't have time.",
    example_ja: "時間がありません。",
    example_zh: "没时间。",
    example_es: "No tengo tiempo."
  },
  {
    id: 36,
    category: "Places",
    korean: "집",
    romanization: "jip",
    en: "House / Home",
    ja: "家",
    zh: "家",
    es: "Casa",
    example_ko: "집에 가고 싶어요.",
    example_en: "I want to go home.",
    example_ja: "家に帰りたいです。",
    example_zh: "我想回家。",
    example_es: "Quiero ir a casa."
  },
  {
    id: 37,
    category: "Places",
    korean: "학교",
    romanization: "hakgyo",
    en: "School",
    ja: "学校",
    zh: "学校",
    es: "Escuela",
    example_ko: "학교에서 공부해요.",
    example_en: "I study at school.",
    example_ja: "学校で勉強します。",
    example_zh: "在学校学习。",
    example_es: "Estudio en la escuela."
  },
  {
    id: 38,
    category: "Places",
    korean: "병원",
    romanization: "byeong-won",
    en: "Hospital",
    ja: "病院",
    zh: "医院",
    es: "Hospital",
    example_ko: "아파서 병원에 갔어요.",
    example_en: "I went to the hospital because I was sick.",
    example_ja: "具合が悪くて病院に行きました。",
    example_zh: "我不舒服去了医院。",
    example_es: "Fui al hospital porque estaba enfermo."
  },
  {
    id: 39,
    category: "Places",
    korean: "은행",
    romanization: "eunhaeng",
    en: "Bank",
    ja: "銀行",
    zh: "银行",
    es: "Banco",
    example_ko: "은행에서 돈을 찾아요.",
    example_en: "I withdraw money from the bank.",
    example_ja: "銀行でお金を下ろします。",
    example_zh: "在银行取钱。",
    example_es: "Saco dinero del banco."
  },
  {
    id: 40,
    category: "Places",
    korean: "식당",
    romanization: "sikdang",
    en: "Restaurant",
    ja: "食堂 / レストラン",
    zh: "餐厅",
    es: "Restaurante",
    example_ko: "이 식당은 음식이 맛있어요.",
    example_en: "The food in this restaurant is delicious.",
    example_ja: "この食堂は食べ物が美味しいです。",
    example_zh: "这家餐厅的菜很好吃。",
    example_es: "La comida en este restaurante es deliciosa."
  },
  {
    id: 41,
    category: "Shopping",
    korean: "돈",
    romanization: "don",
    en: "Money",
    ja: "お金",
    zh: "钱",
    es: "Dinero",
    example_ko: "돈이 많이 필요해요.",
    example_en: "I need a lot of money.",
    example_ja: "お金がたくさん必要です。",
    example_zh: "需要很多钱。",
    example_es: "Necesito mucho dinero."
  },
  {
    id: 42,
    category: "Shopping",
    korean: "카드",
    romanization: "kadeu",
    en: "Card",
    ja: "カード",
    zh: "卡",
    es: "Tarjeta",
    example_ko: "카드로 계산할게요.",
    example_en: "I will pay by card.",
    example_ja: "カードで払います。",
    example_zh: "我用卡付钱。",
    example_es: "Pagaré con tarjeta."
  },
  {
    id: 43,
    category: "Shopping",
    korean: "얼마",
    romanization: "eolma",
    en: "How much",
    ja: "いくら",
    zh: "多少",
    es: "Cuánto",
    example_ko: "이거 얼마예요?",
    example_en: "How much is this?",
    example_ja: "これはいくらですか？",
    example_zh: "这个多少钱？",
    example_es: "¿Cuánto cuesta esto?"
  },
  {
    id: 44,
    category: "Shopping",
    korean: "옷",
    romanization: "ot",
    en: "Clothes",
    ja: "服",
    zh: "衣服",
    es: "Ropa",
    example_ko: "예쁜 옷을 샀어요.",
    example_en: "I bought pretty clothes.",
    example_ja: "可愛い服を買いました。",
    example_zh: "买了漂亮的衣服。",
    example_es: "Compré ropa bonita."
  },
  {
    id: 45,
    category: "Shopping",
    korean: "가방",
    romanization: "gabang",
    en: "Bag",
    ja: "鞄",
    zh: "包",
    es: "Bolso / Mochila",
    example_ko: "가방 안에 책이 있어요.",
    example_en: "There is a book in the bag.",
    example_ja: "鞄の中に本があります。",
    example_zh: "包里有书。",
    example_es: "Hay un libro en el bolso."
  },
  {
    id: 46,
    category: "Health",
    korean: "아프다",
    romanization: "apeuda",
    en: "To be sick / painful",
    ja: "痛い / 病気だ",
    zh: "疼 / 生病",
    es: "Estar enfermo / Doler",
    example_ko: "머리가 너무 아파요.",
    example_en: "My head hurts a lot.",
    example_ja: "頭がとても痛いです。",
    example_zh: "头很疼。",
    example_es: "Me duele mucho la cabeza."
  },
  {
    id: 47,
    category: "Health",
    korean: "약",
    romanization: "yak",
    en: "Medicine",
    ja: "薬",
    zh: "药",
    es: "Medicina",
    example_ko: "약을 먹고 좀 쉬세요.",
    example_en: "Take some medicine and rest.",
    example_ja: "薬を飲んで少し休んでください。",
    example_zh: "吃点药休息一下。",
    example_es: "Toma medicina y descansa un poco."
  },
  {
    id: 48,
    category: "Health",
    korean: "감기",
    romanization: "gamgi",
    en: "Cold (illness)",
    ja: "風邪",
    zh: "感冒",
    es: "Resfriado",
    example_ko: "감기에 걸렸어요.",
    example_en: "I caught a cold.",
    example_ja: "風邪を引きました。",
    example_zh: "我感冒了。",
    example_es: "Me he resfriado."
  },
  {
    id: 49,
    category: "Health",
    korean: "병원",
    romanization: "byeong-won",
    en: "Hospital",
    ja: "病院",
    zh: "医院",
    es: "Hospital",
    example_ko: "병원은 어디에 있어요?",
    example_en: "Where is the hospital?",
    example_ja: "病院はどこにありますか？",
    example_zh: "医院在哪里？",
    example_es: "¿Dónde está el hospital?"
  },
  {
    id: 50,
    category: "Health",
    korean: "의사",
    romanization: "uisa",
    en: "Doctor",
    ja: "医者",
    zh: "医生",
    es: "Médico",
    example_ko: "의사 선생님이 친절해요.",
    example_en: "The doctor is kind.",
    example_ja: "お医者さんが親切です。",
    example_zh: "医生很亲切。",
    example_es: "El médico es amable."
  },
  {
    id: 51,
    category: "Nature",
    korean: "산",
    romanization: "san",
    en: "Mountain",
    ja: "山",
    zh: "山",
    es: "Montaña",
    example_ko: "주말에 산에 가요.",
    example_en: "I go to the mountain on weekends.",
    example_ja: "週末に山に行きます。",
    example_zh: "周末去爬山。",
    example_es: "Voy a la montaña los fines de semana."
  },
  {
    id: 52,
    category: "Nature",
    korean: "바다",
    romanization: "bada",
    en: "Sea",
    ja: "海",
    zh: "海",
    es: "Mar",
    example_ko: "바다가 정말 아름다워요.",
    example_en: "The sea is really beautiful.",
    example_ja: "海が本当に美しいです。",
    example_zh: "大海真的很美。",
    example_es: "El mar es realmente hermoso."
  },
  {
    id: 53,
    category: "Nature",
    korean: "하늘",
    romanization: "haneul",
    en: "Sky",
    ja: "空",
    zh: "天空",
    es: "Cielo",
    example_ko: "하늘이 파랗고 맑아요.",
    example_en: "The sky is blue and clear.",
    example_ja: "空が青くて澄んでいます。",
    example_zh: "天空又蓝又清澈。",
    example_es: "El cielo está azul y despejado."
  },
  {
    id: 54,
    category: "Nature",
    korean: "꽃",
    romanization: "kkot",
    en: "Flower",
    ja: "花",
    zh: "花",
    es: "Flor",
    example_ko: "정원에 꽃이 피었어요.",
    example_en: "Flowers bloomed in the garden.",
    example_ja: "庭に花が咲きました。",
    example_zh: "花园里的花开了。",
    example_es: "Las flores florecieron en el jardín."
  },
  {
    id: 55,
    category: "Nature",
    korean: "나무",
    romanization: "namu",
    en: "Tree",
    ja: "木",
    zh: "树",
    es: "Árbol",
    example_ko: "나무 그늘 아래에서 쉬어요.",
    example_en: "I rest under the shade of a tree.",
    example_ja: "木の木陰で休みます。",
    example_zh: "在树荫下休息。",
    example_es: "Descanso bajo la sombra de un árbol."
  },
  {
    id: 56,
    category: "Food",
    korean: "사과",
    romanization: "sagwa",
    en: "Apple",
    ja: "りんご",
    zh: "苹果",
    es: "Manzana",
    example_ko: "아침에 사과를 먹어요.",
    example_en: "I eat an apple in the morning.",
    example_ja: "朝にりんごを食べます。",
    example_zh: "早上吃苹果。",
    example_es: "Como una manzana por la mañana."
  },
  {
    id: 57,
    category: "Food",
    korean: "우유",
    romanization: "uyu",
    en: "Milk",
    ja: "牛乳",
    zh: "牛奶",
    es: "Leche",
    example_ko: "우유를 마시면 키가 커요.",
    example_en: "If you drink milk, you grow tall.",
    example_ja: "牛乳を飲むと背が伸びます。",
    example_zh: "喝牛奶会长高。",
    example_es: "Si bebes leche, creces."
  },
  {
    id: 58,
    category: "Food",
    korean: "빵",
    romanization: "ppang",
    en: "Bread",
    ja: "パン",
    zh: "面包",
    es: "Pan",
    example_ko: "빵집에서 맛있는 빵을 샀어요.",
    example_en: "I bought delicious bread at the bakery.",
    example_ja: "パン屋で美味しいパンを買いました。",
    example_zh: "在面包店买了美味的面包。",
    example_es: "Compré pan delicioso en la panadería."
  },
  {
    id: 59,
    category: "Food",
    korean: "고기",
    romanization: "gogi",
    en: "Meat",
    ja: "肉",
    zh: "肉",
    es: "Carne",
    example_ko: "저녁으로 고기를 구웠어요.",
    example_en: "I grilled meat for dinner.",
    example_ja: "夕食に肉を焼きました。",
    example_zh: "晚饭烤了肉。",
    example_es: "Asé carne para la cena."
  },
  {
    id: 60,
    category: "Food",
    korean: "채소",
    romanization: "chaeso",
    en: "Vegetable",
    ja: "野菜",
    zh: "蔬菜",
    es: "Verdura",
    example_ko: "채소를 많이 먹어야 해요.",
    example_en: "You should eat a lot of vegetables.",
    example_ja: "野菜をたくさん食べなければなりません。",
    example_zh: "应该多吃蔬菜。",
    example_es: "Debes comer muchas verduras."
  },
  {
    id: 61,
    category: "Verbs",
    korean: "읽다",
    romanization: "ikda",
    en: "To read",
    ja: "読む",
    zh: "读",
    es: "Leer",
    example_ko: "책을 읽고 있어요.",
    example_en: "I am reading a book.",
    example_ja: "本を読んでいます。",
    example_zh: "正在看书。",
    example_es: "Estoy leyendo un libro."
  },
  {
    id: 62,
    category: "Verbs",
    korean: "쓰다",
    romanization: "sseuda",
    en: "To write",
    ja: "書く",
    zh: "写",
    es: "Escribir",
    example_ko: "편지를 써요.",
    example_en: "I write a letter.",
    example_ja: "手紙を書きます。",
    example_zh: "写信。",
    example_es: "Escribo una carta."
  },
  {
    id: 63,
    category: "Verbs",
    korean: "듣다",
    romanization: "deutda",
    en: "To listen",
    ja: "聞く",
    zh: "听",
    es: "Escuchar",
    example_ko: "음악을 들어요.",
    example_en: "I listen to music.",
    example_ja: "音楽を聞きます。",
    example_zh: "听音乐。",
    example_es: "Escucho música."
  },
  {
    id: 64,
    category: "Verbs",
    korean: "보다",
    romanization: "boda",
    en: "To see / watch",
    ja: "見る",
    zh: "看",
    es: "Ver / Mirar",
    example_ko: "영화를 봐요.",
    example_en: "I watch a movie.",
    example_ja: "映画を見ます。",
    example_zh: "看电影。",
    example_es: "Veo una película."
  },
  {
    id: 65,
    category: "Verbs",
    korean: "말하다",
    romanization: "malhada",
    en: "To speak / say",
    ja: "話す / 言う",
    zh: "说",
    es: "Hablar / Decir",
    example_ko: "천천히 말해 주세요.",
    example_en: "Please speak slowly.",
    example_ja: "ゆっくり話してください。",
    example_zh: "请慢点说。",
    example_es: "Por favor, hable despacio."
  },
  {
    id: 66,
    category: "Adjectives",
    korean: "멀다",
    romanization: "meolda",
    en: "To be far",
    ja: "遠い",
    zh: "远",
    es: "Lejos",
    example_ko: "회사가 너무 멀어요.",
    example_en: "The office is too far.",
    example_ja: "会社が遠すぎます。",
    example_zh: "公司太远了。",
    example_es: "La oficina está demasiado lejos."
  },
  {
    id: 67,
    category: "Adjectives",
    korean: "가깝다",
    romanization: "gakkapda",
    en: "To be near",
    ja: "近い",
    zh: "近",
    es: "Cerca",
    example_ko: "역에서 가까워요.",
    example_en: "It's near the station.",
    example_ja: "駅から近いです。",
    example_zh: "离车站很近。",
    example_es: "Está cerca de la estación."
  },
  {
    id: 68,
    category: "Adjectives",
    korean: "덥다",
    romanization: "deopda",
    en: "To be hot (weather)",
    ja: "暑い",
    zh: "热",
    es: "Calor",
    example_ko: "여름은 너무 더워요.",
    example_en: "Summer is too hot.",
    example_ja: "夏はとても暑いです。",
    example_zh: "夏天太热了。",
    example_es: "El verano es demasiado caluroso."
  },
  {
    id: 69,
    category: "Adjectives",
    korean: "춥다",
    romanization: "chupda",
    en: "To be cold (weather)",
    ja: "寒い",
    zh: "冷",
    es: "Frío",
    example_ko: "겨울은 정말 추워요.",
    example_en: "Winter is really cold.",
    example_ja: "冬は本当に寒いです。",
    example_zh: "冬天真的很冷。",
    example_es: "El invierno es realmente frío."
  },
  {
    id: 70,
    category: "Adjectives",
    korean: "어렵다",
    romanization: "eoryeopda",
    en: "To be difficult",
    ja: "難しい",
    zh: "难",
    es: "Difícil",
    example_ko: "한국어 공부가 어려워요.",
    example_en: "Studying Korean is difficult.",
    example_ja: "韓国語の勉強が難しいです。",
    example_zh: "学习韩语很难。",
    example_es: "Estudiar coreano es difícil."
  },
  {
    id: 71,
    category: "Travel",
    korean: "지하철",
    romanization: "jihacheol",
    en: "Subway",
    ja: "地下鉄",
    zh: "地铁",
    es: "Metro",
    example_ko: "지하철을 타고 가요.",
    example_en: "I go by subway.",
    example_ja: "地下鉄に乗って行きます。",
    example_zh: "坐地铁去。",
    example_es: "Voy en metro."
  },
  {
    id: 72,
    category: "Travel",
    korean: "버스",
    romanization: "beoseu",
    en: "Bus",
    ja: "バス",
    zh: "公交车",
    es: "Autobús",
    example_ko: "버스 정류장이 어디예요?",
    example_en: "Where is the bus stop?",
    example_ja: "バス停はどこですか？",
    example_zh: "公交车站在哪里？",
    example_es: "¿Dónde está la parada de autobús?"
  },
  {
    id: 73,
    category: "Travel",
    korean: "택시",
    romanization: "taeksi",
    en: "Taxi",
    ja: "タクシー",
    zh: "出租车",
    es: "Taxi",
    example_ko: "택시를 잡아요.",
    example_en: "I catch a taxi.",
    example_ja: "タクシーを捕まえます。",
    example_zh: "打车。",
    example_es: "Cojo un taxi."
  },
  {
    id: 74,
    category: "Travel",
    korean: "기차",
    romanization: "gicha",
    en: "Train",
    ja: "列車 / 電車",
    zh: "火车",
    es: "Tren",
    example_ko: "기차를 타고 여행해요.",
    example_en: "I travel by train.",
    example_ja: "列車に乗って旅行します。",
    example_zh: "坐火车旅行。",
    example_es: "Viajo en tren."
  },
  {
    id: 75,
    category: "Travel",
    korean: "자전거",
    romanization: "jajeon-geo",
    en: "Bicycle",
    ja: "自転車",
    zh: "自行车",
    es: "Bicicleta",
    example_ko: "공원에서 자전거를 타요.",
    example_en: "I ride a bicycle in the park.",
    example_ja: "公園で自転車に乗ります。",
    example_zh: "在公园骑自行车。",
    example_es: "Monto en bicicleta en el parque."
  },
  {
    id: 76,
    category: "Feelings",
    korean: "행복하다",
    romanization: "haengbokhada",
    en: "To be happy",
    ja: "幸せだ",
    zh: "幸福",
    es: "Feliz",
    example_ko: "정말 행복해요.",
    example_en: "I'm really happy.",
    example_ja: "本当に幸せです。",
    example_zh: "真的很幸福。",
    example_es: "Soy muy feliz."
  },
  {
    id: 77,
    category: "Feelings",
    korean: "슬프다",
    romanization: "seulpeuda",
    en: "To be sad",
    ja: "悲しい",
    zh: "悲伤",
    es: "Triste",
    example_ko: "슬픈 영화를 봤어요.",
    example_en: "I watched a sad movie.",
    example_ja: "悲しい映画を見ました。",
    example_zh: "我看了一部悲伤的电影。",
    example_es: "Vi una película triste."
  },
  {
    id: 78,
    category: "Feelings",
    korean: "기쁘다",
    romanization: "gippeuda",
    en: "To be glad / pleased",
    ja: "嬉しい",
    zh: "高兴",
    es: "Alegre",
    example_ko: "선물을 받아서 기뻐요.",
    example_en: "I'm glad because I got a gift.",
    example_ja: "プレゼントをもらって嬉しいです。",
    example_zh: "收到礼物很高兴。",
    example_es: "Me alegro de haber recibido un regalo."
  },
  {
    id: 79,
    category: "Feelings",
    korean: "피곤하다",
    romanization: "pigonhada",
    en: "To be tired",
    ja: "疲れている",
    zh: "累",
    es: "Cansado",
    example_ko: "일이 많아서 피곤해요.",
    example_en: "I'm tired because there's a lot of work.",
    example_ja: "仕事が多くて疲れています。",
    example_zh: "工作很多，很累。",
    example_es: "Estoy cansado porque hay mucho trabajo."
  },
  {
    id: 80,
    category: "Feelings",
    korean: "심심하다",
    romanization: "simsimhada",
    en: "To be bored",
    ja: "退屈だ",
    zh: "无聊",
    es: "Aburrido",
    example_ko: "심심할 때 뭐 해요?",
    example_en: "What do you do when you're bored?",
    example_ja: "退屈な時何をしますか？",
    example_zh: "无聊的时候做什么？",
    example_es: "¿Qué haces cuando estás aburrido?"
  },
  {
    id: 81,
    category: "Daily Life",
    korean: "일어나다",
    romanization: "ireonada",
    en: "To wake up / get up",
    ja: "起きる",
    zh: "起床",
    es: "Despertarse",
    example_ko: "아침 7시에 일어나요.",
    example_en: "I wake up at 7 AM.",
    example_ja: "朝7時に起きます。",
    example_zh: "早上7点起床。",
    example_es: "Me despierto a las 7 de la mañana."
  },
  {
    id: 82,
    category: "Daily Life",
    korean: "씻다",
    romanization: "ssitda",
    en: "To wash",
    ja: "洗う",
    zh: "洗",
    es: "Lavar",
    example_ko: "손을 깨끗이 씻어요.",
    example_en: "I wash my hands clean.",
    example_ja: "手を綺麗に洗います。",
    example_zh: "把手洗干净。",
    example_es: "Me lavo las manos bien."
  },
  {
    id: 83,
    category: "Daily Life",
    korean: "일하다",
    romanization: "ilhada",
    en: "To work",
    ja: "働く",
    zh: "工作",
    es: "Trabajar",
    example_ko: "회사에서 열심히 일해요.",
    example_en: "I work hard at the company.",
    example_ja: "会社で一生懸命働きます。",
    example_zh: "在公司努力工作。",
    example_es: "Trabajo duro en la empresa."
  },
  {
    id: 84,
    category: "Daily Life",
    korean: "공부하다",
    romanization: "gongbuhada",
    en: "To study",
    ja: "勉強する",
    zh: "学习",
    es: "Estudiar",
    example_ko: "도서관에서 공부해요.",
    example_en: "I study in the library.",
    example_ja: "図書館で勉強します。",
    example_zh: "在图书馆学习。",
    example_es: "Estudio en la biblioteca."
  },
  {
    id: 85,
    category: "Daily Life",
    korean: "쉬다",
    romanization: "swida",
    en: "To rest",
    ja: "休む",
    zh: "休息",
    es: "Descansar",
    example_ko: "집에서 편하게 쉬어요.",
    example_en: "I rest comfortably at home.",
    example_ja: "家でゆっくり休みます。",
    example_zh: "在家里舒服地休息。",
    example_es: "Descanso cómodamente en casa."
  },
  {
    id: 86,
    category: "Nature",
    korean: "해",
    romanization: "hae",
    en: "Sun",
    ja: "太陽",
    zh: "太阳",
    es: "Sol",
    example_ko: "해가 떴어요.",
    example_en: "The sun has risen.",
    example_ja: "太陽が昇りました。",
    example_zh: "太阳出来了。",
    example_es: "El sol ha salido."
  },
  {
    id: 87,
    category: "Nature",
    korean: "달",
    romanization: "dal",
    en: "Moon",
    ja: "月",
    zh: "月亮",
    es: "Luna",
    example_ko: "달이 참 밝아요.",
    example_en: "The moon is very bright.",
    example_ja: "月がとても明るいです。",
    example_zh: "月亮真亮。",
    example_es: "La luna es muy brillante."
  },
  {
    id: 88,
    category: "Nature",
    korean: "별",
    romanization: "byeol",
    en: "Star",
    ja: "星",
    zh: "星星",
    es: "Estrella",
    example_ko: "밤하늘에 별이 많아요.",
    example_en: "There are many stars in the night sky.",
    example_ja: "夜空に星がたくさんあります。",
    example_zh: "夜空里有很多星星。",
    example_es: "Hay muchas estrellas en el cielo nocturno."
  },
  {
    id: 89,
    category: "Nature",
    korean: "바람",
    romanization: "baram",
    en: "Wind",
    ja: "風",
    zh: "风",
    es: "Viento",
    example_ko: "바람이 시원하게 불어요.",
    example_en: "The wind is blowing coolly.",
    example_ja: "風が涼しく吹いています。",
    example_zh: "凉风习习。",
    example_es: "El viento sopla fresco."
  },
  {
    id: 90,
    category: "Nature",
    korean: "비",
    romanization: "bi",
    en: "Rain",
    ja: "雨",
    zh: "雨",
    es: "Lluvia",
    example_ko: "비가 오고 있어요.",
    example_en: "It is raining.",
    example_ja: "雨が降っています。",
    example_zh: "正在下雨。",
    example_es: "Está lloviendo."
  },
  {
    id: 91,
    category: "School",
    korean: "학생",
    romanization: "haksaeng",
    en: "Student",
    ja: "学生",
    zh: "学生",
    es: "Estudiante",
    example_ko: "저는 대학생이에요.",
    example_en: "I am a college student.",
    example_ja: "私は大学生です。",
    example_zh: "我是大学生。",
    example_es: "Soy estudiante universitario."
  },
  {
    id: 92,
    category: "School",
    korean: "선생님",
    romanization: "seonsaengnim",
    en: "Teacher",
    ja: "先生",
    zh: "老师",
    es: "Profesor/a",
    example_ko: "선생님이 가르쳐 주셨어요.",
    example_en: "The teacher taught me.",
    example_ja: "先生が教えてくれました。",
    example_zh: "老师教了我。",
    example_es: "El profesor me enseñó."
  },
  {
    id: 93,
    category: "School",
    korean: "책",
    romanization: "chaek",
    en: "Book",
    ja: "本",
    zh: "书",
    es: "Libro",
    example_ko: "책을 읽는 것을 좋아해요.",
    example_en: "I like reading books.",
    example_ja: "本を読むのが好きです。",
    example_zh: "我喜欢读书。",
    example_es: "Me gusta leer libros."
  },
  {
    id: 94,
    category: "School",
    korean: "연필",
    romanization: "yeonpil",
    en: "Pencil",
    ja: "鉛筆",
    zh: "铅笔",
    es: "Lápiz",
    example_ko: "연필로 글씨를 써요.",
    example_en: "I write with a pencil.",
    example_ja: "鉛筆で文字を書きます。",
    example_zh: "用铅笔写字。",
    example_es: "Escribo con un lápiz."
  },
  {
    id: 95,
    category: "School",
    korean: "공책",
    romanization: "gongchaek",
    en: "Notebook",
    ja: "ノート",
    zh: "笔记本",
    es: "Cuaderno",
    example_ko: "공책에 메모를 해요.",
    example_en: "I take notes in a notebook.",
    example_ja: "ノートにメモをします。",
    example_zh: "在笔记本上做笔记。",
    example_es: "Tomo notas en un cuaderno."
  },
  {
    id: 96,
    category: "Verbs",
    korean: "만나다",
    romanization: "mannada",
    en: "To meet",
    ja: "会う",
    zh: "见面",
    es: "Encontrarse / Reunirse",
    example_ko: "친구를 만나러 가요.",
    example_en: "I'm going to meet a friend.",
    example_ja: "友達に会いに行きます。",
    example_zh: "去见朋友。",
    example_es: "Voy a encontrarme con un amigo."
  },
  {
    id: 97,
    category: "Verbs",
    korean: "기다리다",
    romanization: "gidarida",
    en: "To wait",
    ja: "待つ",
    zh: "等待",
    es: "Esperar",
    example_ko: "여기서 기다려 주세요.",
    example_en: "Please wait here.",
    example_ja: "ここで待ってください。",
    example_zh: "请在这里等。",
    example_es: "Por favor, espera aquí."
  },
  {
    id: 98,
    category: "Verbs",
    korean: "사다",
    romanization: "sada",
    en: "To buy",
    ja: "買う",
    zh: "买",
    es: "Comprar",
    example_ko: "슈퍼에서 물을 샀어요.",
    example_en: "I bought water at the supermarket.",
    example_ja: "スーパーで水を買いました。",
    example_zh: "在超市买了水。",
    example_es: "Compré agua en el supermercado."
  },
  {
    id: 99,
    category: "Verbs",
    korean: "주다",
    romanization: "juda",
    en: "To give",
    ja: "あげる / くれる",
    zh: "给",
    es: "Dar",
    example_ko: "동생에게 선물을 줬어요.",
    example_en: "I gave a gift to my younger sibling.",
    example_ja: "弟（妹）にプレゼントをあげました。",
    example_zh: "给弟弟（妹妹）送了礼物。",
    example_es: "Le di un regalo a mi hermano menor."
  },
  {
    id: 100,
    category: "Verbs",
    korean: "배우다",
    romanization: "baeuda",
    en: "To learn",
    ja: "学ぶ / 習う",
    zh: "学习",
    es: "Aprender",
    example_ko: "한국어를 배우고 싶어요.",
    example_en: "I want to learn Korean.",
    example_ja: "韓国語を学びたいです。",
    example_zh: "我想学习韩语。",
    example_es: "Quiero aprender coreano."
  },
  {
    id: 101,
    category: "Adjectives",
    korean: "쉽다",
    romanization: "swipda",
    en: "To be easy",
    ja: "易しい",
    zh: "容易",
    es: "Fácil",
    example_ko: "문제가 정말 쉬워요.",
    example_en: "The problem is really easy.",
    example_ja: "問題が本当に易しいです。",
    example_zh: "题目真的很简单。",
    example_es: "El problema es muy fácil."
  },
  {
    id: 102,
    category: "Adjectives",
    korean: "무겁다",
    romanization: "mugeopda",
    en: "To be heavy",
    ja: "重い",
    zh: "重",
    es: "Pesado",
    example_ko: "가방이 너무 무거워요.",
    example_en: "The bag is too heavy.",
    example_ja: "鞄が重すぎます。",
    example_zh: "包太重了。",
    example_es: "El bolso es demasiado pesado."
  },
  {
    id: 103,
    category: "Adjectives",
    korean: "가볍다",
    romanization: "gabyeopda",
    en: "To be light",
    ja: "軽い",
    zh: "轻",
    es: "Ligero",
    example_ko: "짐이 가벼워서 좋아요.",
    example_en: "I like that the luggage is light.",
    example_ja: "荷物が軽くて良いです。",
    example_zh: "行李很轻，真好。",
    example_es: "Me gusta que el equipaje sea ligero."
  },
  {
    id: 104,
    category: "Adjectives",
    korean: "길다",
    romanization: "gilda",
    en: "To be long",
    ja: "長い",
    zh: "长",
    es: "Largo",
    example_ko: "머리카락이 길어요.",
    example_en: "The hair is long.",
    example_ja: "髪が長いです。",
    example_zh: "头发很长。",
    example_es: "El pelo es largo."
  },
  {
    id: 105,
    category: "Adjectives",
    korean: "짧다",
    romanization: "jjalda",
    en: "To be short",
    ja: "短い",
    zh: "短",
    es: "Corto",
    example_ko: "바지가 너무 짧아요.",
    example_en: "The pants are too short.",
    example_ja: "ズボンが短すぎます。",
    example_zh: "裤子太短了。",
    example_es: "Los pantalones son demasiado cortos."
  },
  {
    id: 106,
    category: "Objects",
    korean: "핸드폰",
    romanization: "haendeupon",
    en: "Cellphone",
    ja: "携帯電話",
    zh: "手机",
    es: "Teléfono móvil",
    example_ko: "핸드폰으로 전화를 해요.",
    example_en: "I make a call with my cellphone.",
    example_ja: "携帯電話で電話をかけます。",
    example_zh: "用手机打电话。",
    example_es: "Hago una llamada con el móvil."
  },
  {
    id: 107,
    category: "Objects",
    korean: "컴퓨터",
    romanization: "keompyuteo",
    en: "Computer",
    ja: "コンピューター",
    zh: "电脑",
    es: "Ordenador",
    example_ko: "컴퓨터로 게임을 해요.",
    example_en: "I play games on the computer.",
    example_ja: "コンピューターでゲームをします。",
    example_zh: "在电脑上玩游戏。",
    example_es: "Juego a juegos en el ordenador."
  },
  {
    id: 108,
    category: "Objects",
    korean: "텔레비전",
    romanization: "tellebijeon",
    en: "Television",
    ja: "テレビ",
    zh: "电视",
    es: "Televisión",
    example_ko: "텔레비전에서 뉴스를 봐요.",
    example_en: "I watch the news on television.",
    example_ja: "テレビでニュースを見ます。",
    example_zh: "在电视上看新闻。",
    example_es: "Veo las noticias en la televisión."
  },
  {
    id: 109,
    category: "Objects",
    korean: "안경",
    romanization: "angyeong",
    en: "Glasses",
    ja: "メガネ",
    zh: "眼镜",
    es: "Gafas",
    example_ko: "안경을 써야 잘 보여요.",
    example_en: "I can see well if I wear glasses.",
    example_ja: "メガネをかけるとよく見えます。",
    example_zh: "戴上眼镜才看得清楚。",
    example_es: "Veo bien si me pongo las gafas."
  },
  {
    id: 110,
    category: "Objects",
    korean: "시계",
    romanization: "sigye",
    en: "Watch / Clock",
    ja: "時計",
    zh: "表",
    es: "Reloj",
    example_ko: "벽에 시계가 걸려 있어요.",
    example_en: "There is a clock hanging on the wall.",
    example_ja: "壁に時計がかかっています。",
    example_zh: "墙上挂着一个表。",
    example_es: "Hay un reloj colgado en la pared."
  },
  {
    id: 111,
    category: "Directions",
    korean: "왼쪽",
    romanization: "oenjjok",
    en: "Left side",
    ja: "左側",
    zh: "左边",
    es: "Izquierda",
    example_ko: "왼쪽으로 가세요.",
    example_en: "Go to the left.",
    example_ja: "左に行ってください。",
    example_zh: "请向左转。",
    example_es: "Ve a la izquierda."
  },
  {
    id: 112,
    category: "Directions",
    korean: "오른쪽",
    romanization: "oreunjjok",
    en: "Right side",
    ja: "右側",
    zh: "右边",
    es: "Derecha",
    example_ko: "오른쪽에 은행이 있어요.",
    example_en: "There is a bank on the right side.",
    example_ja: "右側に銀行があります。",
    example_zh: "右边有一家银行。",
    example_es: "Hay un banco a la derecha."
  },
  {
    id: 113,
    category: "Directions",
    korean: "위",
    romanization: "wi",
    en: "Up / Top / On",
    ja: "上",
    zh: "上",
    es: "Arriba / Encima",
    example_ko: "책상 위에 책이 있어요.",
    example_en: "There is a book on the desk.",
    example_ja: "机の上に本があります。",
    example_zh: "桌子上有一本书。",
    example_es: "Hay un libro encima del escritorio."
  },
  {
    id: 114,
    category: "Directions",
    korean: "아래",
    romanization: "arae",
    en: "Down / Bottom / Under",
    ja: "下",
    zh: "下",
    es: "Abajo / Debajo",
    example_ko: "침대 아래에 양말이 있어요.",
    example_en: "There is a sock under the bed.",
    example_ja: "ベッドの下に靴下があります。",
    example_zh: "床下有一只袜子。",
    example_es: "Hay un calcetín debajo de la cama."
  },
  {
    id: 115,
    category: "Directions",
    korean: "앞",
    romanization: "ap",
    en: "Front",
    ja: "前",
    zh: "前",
    es: "Delante",
    example_ko: "학교 앞에서 기다릴게요.",
    example_en: "I will wait in front of the school.",
    example_ja: "学校の前で待っています。",
    example_zh: "在学校前面等。",
    example_es: "Esperaré delante de la escuela."
  },
  {
    id: 116,
    category: "People",
    korean: "사람",
    romanization: "saram",
    en: "Person",
    ja: "人",
    zh: "人",
    es: "Persona",
    example_ko: "여기에 사람이 많아요.",
    example_en: "There are many people here.",
    example_ja: "ここに人がたくさんいます。",
    example_zh: "这里人很多。",
    example_es: "Hay mucha gente aquí."
  },
  {
    id: 117,
    category: "People",
    korean: "남자",
    romanization: "namja",
    en: "Man",
    ja: "男",
    zh: "男人",
    es: "Hombre",
    example_ko: "저 남자는 누구예요?",
    example_en: "Who is that man?",
    example_ja: "あの男の人は誰ですか？",
    example_zh: "那个男人是谁？",
    example_es: "¿Quién es ese hombre?"
  },
  {
    id: 118,
    category: "People",
    korean: "여자",
    romanization: "yeoja",
    en: "Woman",
    ja: "女",
    zh: "女人",
    es: "Mujer",
    example_ko: "예쁜 여자가 지나가요.",
    example_en: "A pretty woman is passing by.",
    example_ja: "綺麗な女の人が通り過ぎます。",
    example_zh: "一个漂亮的女人路过。",
    example_es: "Una mujer bonita está pasando."
  },
  {
    id: 119,
    category: "People",
    korean: "아이",
    romanization: "ai",
    en: "Child",
    ja: "子供",
    zh: "孩子",
    es: "Niño/a",
    example_ko: "아이가 공을 가지고 놀아요.",
    example_en: "A child is playing with a ball.",
    example_ja: "子供がボールを持って遊んでいます。",
    example_zh: "孩子在玩球。",
    example_es: "Un niño está jugando con una pelota."
  },
  {
    id: 120,
    category: "People",
    korean: "의사",
    romanization: "uisa",
    en: "Doctor",
    ja: "医者",
    zh: "医生",
    es: "Médico",
    example_ko: "제 꿈은 의사가 되는 거예요.",
    example_en: "My dream is to become a doctor.",
    example_ja: "私の夢は医者になることです。",
    example_zh: "我的梦想是当一名医生。",
    example_es: "Mi sueño es ser médico."
  },
  {
    id: 121,
    category: "Daily Life",
    korean: "빨래",
    romanization: "ppallae",
    en: "Laundry",
    ja: "洗濯",
    zh: "洗衣服",
    es: "Lavandería / Colada",
    example_ko: "주말에 빨래를 해요.",
    example_en: "I do laundry on weekends.",
    example_ja: "週末に洗濯をします。",
    example_zh: "周末洗衣服。",
    example_es: "Hago la colada los fines de semana."
  },
  {
    id: 122,
    category: "Daily Life",
    korean: "청소",
    romanization: "cheongso",
    en: "Cleaning",
    ja: "掃除",
    zh: "打扫",
    es: "Limpieza",
    example_ko: "방 청소를 했어요.",
    example_en: "I cleaned the room.",
    example_ja: "部屋の掃除をしました。",
    example_zh: "打扫了房间。",
    example_es: "Limpié la habitación."
  },
  {
    id: 123,
    category: "Daily Life",
    korean: "요리",
    romanization: "yori",
    en: "Cooking",
    ja: "料理",
    zh: "烹饪",
    es: "Cocina / Cocinar",
    example_ko: "요리하는 것을 좋아해요.",
    example_en: "I like cooking.",
    example_ja: "料理をするのが好きです。",
    example_zh: "我喜欢做饭。",
    example_es: "Me gusta cocinar."
  },
  {
    id: 124,
    category: "Daily Life",
    korean: "운동",
    romanization: "undong",
    en: "Exercise / Sports",
    ja: "運動 / スポーツ",
    zh: "运动",
    es: "Ejercicio / Deporte",
    example_ko: "매일 아침 운동을 해요.",
    example_en: "I exercise every morning.",
    example_ja: "毎朝運動をします。",
    example_zh: "每天早上运动。",
    example_es: "Hago ejercicio todas las mañanas."
  },
  {
    id: 125,
    category: "Daily Life",
    korean: "산책",
    romanization: "sanchaek",
    en: "Walk / Stroll",
    ja: "散歩",
    zh: "散步",
    es: "Paseo",
    example_ko: "공원에서 산책을 해요.",
    example_en: "I take a walk in the park.",
    example_ja: "公園で散歩をします。",
    example_zh: "在公园散步。",
    example_es: "Doy un paseo por el parque."
  },
  {
    id: 126,
    category: "Weather",
    korean: "날씨",
    romanization: "nalssi",
    en: "Weather",
    ja: "天気",
    zh: "天气",
    es: "Tiempo (clima)",
    example_ko: "오늘 날씨가 어때요?",
    example_en: "How is the weather today?",
    example_ja: "今日の天気はどうですか？",
    example_zh: "今天天气怎么样？",
    example_es: "¿Cómo está el tiempo hoy?"
  },
  {
    id: 127,
    category: "Weather",
    korean: "맑음",
    romanization: "malgeum",
    en: "Sunny / Clear",
    ja: "晴れ",
    zh: "晴",
    es: "Despejado",
    example_ko: "하늘이 아주 맑아요.",
    example_en: "The sky is very clear.",
    example_ja: "空がとても晴れています。",
    example_zh: "天空很晴朗。",
    example_es: "El cielo está muy despejado."
  },
  {
    id: 128,
    category: "Weather",
    korean: "흐림",
    romanization: "heurim",
    en: "Cloudy",
    ja: "曇り",
    zh: "阴",
    es: "Nublado",
    example_ko: "오늘은 조금 흐려요.",
    example_en: "It is a bit cloudy today.",
    example_ja: "今日は少し曇っています。",
    example_zh: "今天有点阴。",
    example_es: "Hoy está un poco nublado."
  },
  {
    id: 129,
    category: "Weather",
    korean: "눈",
    romanization: "nun",
    en: "Snow",
    ja: "雪",
    zh: "雪",
    es: "Nieve",
    example_ko: "겨울에 눈이 와요.",
    example_en: "It snows in winter.",
    example_ja: "冬に雪が降ります。",
    example_zh: "冬天会下雪。",
    example_es: "Nieva en invierno."
  },
  {
    id: 130,
    category: "Weather",
    korean: "안개",
    romanization: "angae",
    en: "Fog",
    ja: "霧",
    zh: "雾",
    es: "Niebla",
    example_ko: "안개가 끼어서 안 보여요.",
    example_en: "It's foggy, so I can't see.",
    example_ja: "霧が出ていて見えません。",
    example_zh: "起雾了，看不清。",
    example_es: "Hay niebla, así que no puedo ver."
  },
  {
    id: 131,
    category: "Food",
    korean: "소금",
    romanization: "sogeum",
    en: "Salt",
    ja: "塩",
    zh: "盐",
    es: "Sal",
    example_ko: "음식이 짜면 소금을 넣지 마세요.",
    example_en: "If the food is salty, don't add salt.",
    example_ja: "食べ物がしょっぱいなら塩を入れないでください。",
    example_zh: "如果菜太咸，就别加盐了。",
    example_es: "Si la comida está salada, no añadas sal."
  },
  {
    id: 132,
    category: "Food",
    korean: "설탕",
    romanization: "seoltang",
    en: "Sugar",
    ja: "砂糖",
    zh: "糖",
    es: "Azúcar",
    example_ko: "커피에 설탕을 넣어요.",
    example_en: "I put sugar in my coffee.",
    example_ja: "コーヒーに砂糖を入れます。",
    example_zh: "咖啡里加糖。",
    example_es: "Pongo azúcar en mi café."
  },
  {
    id: 133,
    category: "Food",
    korean: "고추장",
    romanization: "gochujang",
    en: "Red chili paste",
    ja: "コチュジャン",
    zh: "辣椒酱",
    es: "Pasta de chile rojo",
    example_ko: "비빔밥에 고추장을 넣어요.",
    example_en: "I put gochujang in bibimbap.",
    example_ja: "ビビンバにコチュジャンを入れます。",
    example_zh: "拌饭里加辣椒酱。",
    example_es: "Pongo gochujang en el bibimbap."
  },
  {
    id: 134,
    category: "Food",
    korean: "김",
    romanization: "gim",
    en: "Seaweed",
    ja: "海苔",
    zh: "海苔 / 紫菜",
    es: "Algas",
    example_ko: "김에 밥을 싸서 먹어요.",
    example_en: "I eat rice wrapped in seaweed.",
    example_ja: "海苔にご飯を巻いて食べます。",
    example_zh: "用海苔裹饭吃。",
    example_es: "Como arroz envuelto en algas."
  },
  {
    id: 135,
    category: "Food",
    korean: "라면",
    romanization: "ramyeon",
    en: "Ramen",
    ja: "ラーメン",
    zh: "拉面",
    es: "Ramen",
    example_ko: "밤에 라면을 먹으면 맛있어요.",
    example_en: "Ramen is delicious at night.",
    example_ja: "夜にラーメンを食べると美味しいです。",
    example_zh: "晚上吃拉面很好吃。",
    example_es: "El ramen es delicioso por la noche."
  },
  {
    id: 136,
    category: "Verbs",
    korean: "사랑하다",
    romanization: "saranghada",
    en: "To love",
    ja: "愛する",
    zh: "爱",
    es: "Amar",
    example_ko: "가족을 아주 사랑해요.",
    example_en: "I love my family very much.",
    example_ja: "家族をとても愛しています。",
    example_zh: "我很爱我的家人。",
    example_es: "Amo mucho a mi familia."
  },
  {
    id: 137,
    category: "Verbs",
    korean: "좋아하다",
    romanization: "joahada",
    en: "To like",
    ja: "好きだ",
    zh: "喜欢",
    es: "Gustar",
    example_ko: "한국 음악을 좋아해요.",
    example_en: "I like Korean music.",
    example_ja: "韓国の音楽が好きです。",
    example_zh: "我喜欢韩国音乐。",
    example_es: "Me gusta la música coreana."
  },
  {
    id: 138,
    category: "Verbs",
    korean: "싫어하다",
    romanization: "sireohada",
    en: "To dislike / hate",
    ja: "嫌いだ",
    zh: "不喜欢 / 讨厌",
    es: "No gustar / Odiar",
    example_ko: "매운 음식을 싫어해요.",
    example_en: "I dislike spicy food.",
    example_ja: "辛い食べ物が嫌いです。",
    example_zh: "我不喜欢辣的食物。",
    example_es: "No me gusta la comida picante."
  },
  {
    id: 139,
    category: "Verbs",
    korean: "생각하다",
    romanization: "saenggakhada",
    en: "To think",
    ja: "考える",
    zh: "想 / 认为",
    es: "Pensar",
    example_ko: "문제를 다시 생각해 보세요.",
    example_en: "Please think about the problem again.",
    example_ja: "問題をもう一度考えてみてください。",
    example_zh: "请再考虑一下这个问题。",
    example_es: "Por favor, piensa en el problema otra vez."
  },
  {
    id: 140,
    category: "Verbs",
    korean: "노래하다",
    romanization: "noraehada",
    en: "To sing",
    ja: "歌う",
    zh: "唱歌",
    es: "Cantar",
    example_ko: "친구들과 노래방에서 노래해요.",
    example_en: "I sing with friends at the karaoke.",
    example_ja: "友達とカラオケで歌います。",
    example_zh: "和朋友们在歌厅唱歌。",
    example_es: "Canto con mis amigos en el karaoke."
  },
  {
    id: 141,
    category: "Adjectives",
    korean: "재미있다",
    romanization: "jaemiitda",
    en: "To be interesting / fun",
    ja: "面白い",
    zh: "有趣",
    es: "Interesante / Divertido",
    example_ko: "이 영화는 정말 재미있어요.",
    example_en: "This movie is really interesting.",
    example_ja: "この映画は本当に面白いです。",
    example_zh: "这部电影很有趣。",
    example_es: "Esta película es muy divertida."
  },
  {
    id: 142,
    category: "Adjectives",
    korean: "맛있다",
    romanization: "masitda",
    en: "To be delicious",
    ja: "美味しい",
    zh: "好吃",
    es: "Delicioso",
    example_ko: "한국 음식이 정말 맛있어요.",
    example_en: "Korean food is really delicious.",
    example_ja: "韓国料理が本当に美味しいです。",
    example_zh: "韩国菜很好吃。",
    example_es: "La comida coreana es muy deliciosa."
  },
  {
    id: 143,
    category: "Adjectives",
    korean: "예쁘다",
    romanization: "yeppeuda",
    en: "To be pretty",
    ja: "可愛い / 美しい",
    zh: "漂亮",
    es: "Bonito/a",
    example_ko: "꽃이 정말 예뻐요.",
    example_en: "The flower is really pretty.",
    example_ja: "花が本当に可愛いです。",
    example_zh: "花很漂亮。",
    example_es: "La flor es muy bonita."
  },
  {
    id: 144,
    category: "Adjectives",
    korean: "멋있다",
    romanization: "meositda",
    en: "To be cool / stylish",
    ja: "かっこいい",
    zh: "帅 / 酷",
    es: "Guay / Elegante",
    example_ko: "옷이 정말 멋있네요.",
    example_en: "The clothes are really cool.",
    example_ja: "服がとてもかっこいいですね。",
    example_zh: "衣服很帅气。",
    example_es: "La ropa es muy guay."
  },
  {
    id: 145,
    category: "Adjectives",
    korean: "친절하다",
    romanization: "chinjeolhada",
    en: "To be kind",
    ja: "親切だ",
    zh: "亲切",
    es: "Amable",
    example_ko: "한국 사람들은 친절해요.",
    example_en: "Korean people are kind.",
    example_ja: "韓国人は親切です。",
    example_zh: "韩国人很亲切。",
    example_es: "La gente coreana es amable."
  },
  {
    id: 146,
    category: "Body",
    korean: "머리",
    romanization: "meori",
    en: "Head / Hair",
    ja: "頭 / 髪",
    zh: "头 / 头发",
    es: "Cabeza / Pelo",
    example_ko: "머리가 아파요.",
    example_en: "My head hurts.",
    example_ja: "頭が痛いです。",
    example_zh: "头疼。",
    example_es: "Me duele la cabeza."
  },
  {
    id: 147,
    category: "Body",
    korean: "눈",
    romanization: "nun",
    en: "Eye",
    ja: "目",
    zh: "眼睛",
    es: "Ojo",
    example_ko: "눈이 커서 예뻐요.",
    example_en: "Eyes are big and pretty.",
    example_ja: "目が大きくて可愛いです。",
    example_zh: "眼睛很大，很漂亮。",
    example_es: "Los ojos son grandes y bonitos."
  },
  {
    id: 148,
    category: "Body",
    korean: "코",
    romanization: "ko",
    en: "Nose",
    ja: "鼻",
    zh: "鼻子",
    es: "Nariz",
    example_ko: "코가 높아요.",
    example_en: "The nose is high (well-defined).",
    example_ja: "鼻が高いです。",
    example_zh: "鼻子很高。",
    example_es: "La nariz es alta."
  },
  {
    id: 149,
    category: "Body",
    korean: "입",
    romanization: "ip",
    en: "Mouth",
    ja: "口",
    zh: "嘴",
    es: "Boca",
    example_ko: "입을 크게 벌리세요.",
    example_en: "Open your mouth wide.",
    example_ja: "口を大きく開けてください。",
    example_zh: "把嘴张大。",
    example_es: "Abre bien la boca."
  },
  {
    id: 150,
    category: "Body",
    korean: "귀",
    romanization: "gwi",
    en: "Ear",
    ja: "耳",
    zh: "耳朵",
    es: "Oreja",
    example_ko: "귀가 잘 안 들려요.",
    example_en: "I can't hear well.",
    example_ja: "耳がよく聞こえません。",
    example_zh: "耳朵听不清。",
    example_es: "No oigo bien."
  },
  {
    id: 151,
    category: "Body",
    korean: "손",
    romanization: "son",
    en: "Hand",
    ja: "手",
    zh: "手",
    es: "Mano",
    example_ko: "손을 잡아요.",
    example_en: "Hold hands.",
    example_ja: "手を繋ぎます。",
    example_zh: "握手。",
    example_es: "Coger de la mano."
  },
  {
    id: 152,
    category: "Body",
    korean: "발",
    romanization: "bal",
    en: "Foot",
    ja: "足",
    zh: "脚",
    es: "Pie",
    example_ko: "발이 아파서 못 걸어요.",
    example_en: "My feet hurt so I can't walk.",
    example_ja: "足が痛くて歩けません。",
    example_zh: "脚疼，走不动了。",
    example_es: "Me duelen los pies, así que no puedo caminar."
  },
  {
    id: 153,
    category: "Body",
    korean: "다리",
    romanization: "dari",
    en: "Leg",
    ja: "脚",
    zh: "腿",
    es: "Pierna",
    example_ko: "다리가 길어요.",
    example_en: "The legs are long.",
    example_ja: "脚が長いです。",
    example_zh: "腿很长。",
    example_es: "Las piernas son largas."
  },
  {
    id: 154,
    category: "Body",
    korean: "팔",
    romanization: "pal",
    en: "Arm",
    ja: "腕",
    zh: "胳膊",
    es: "Brazo",
    example_ko: "팔이 가늘어요.",
    example_en: "The arms are thin.",
    example_ja: "腕が細いです。",
    example_zh: "胳膊很细。",
    example_es: "Los brazos son delgados."
  },
  {
    id: 155,
    category: "Body",
    korean: "어깨",
    romanization: "eokkae",
    en: "Shoulder",
    ja: "肩",
    zh: "肩膀",
    es: "Hombro",
    example_ko: "어깨가 무거워요.",
    example_en: "My shoulders feel heavy.",
    example_ja: "肩が重いです。",
    example_zh: "肩膀很沉。",
    example_es: "Los hombros me pesan."
  },
  {
    id: 156,
    category: "Colors",
    korean: "빨간색",
    romanization: "ppalgansaek",
    en: "Red",
    ja: "赤",
    zh: "红色",
    es: "Rojo",
    example_ko: "사과는 빨간색이에요.",
    example_en: "Apples are red.",
    example_ja: "りんごは赤いです。",
    example_zh: "苹果是红色的。",
    example_es: "Las manzanas son rojas."
  },
  {
    id: 157,
    category: "Colors",
    korean: "파란색",
    romanization: "paransaek",
    en: "Blue",
    ja: "青",
    zh: "蓝色",
    es: "Azul",
    example_ko: "하늘은 파란색이에요.",
    example_en: "The sky is blue.",
    example_ja: "空は青いです。",
    example_zh: "天空是蓝色的。",
    example_es: "El cielo es azul."
  },
  {
    id: 158,
    category: "Colors",
    korean: "노란색",
    romanization: "noransaek",
    en: "Yellow",
    ja: "黄色",
    zh: "黄色",
    es: "Amarillo",
    example_ko: "바나나는 노란색이에요.",
    example_en: "Bananas are yellow.",
    example_ja: "バナナは黄色いです。",
    example_zh: "香蕉是黄色的。",
    example_es: "Los plátanos son amarillos."
  },
  {
    id: 159,
    category: "Colors",
    korean: "초록색",
    romanization: "choroksaek",
    en: "Green",
    ja: "緑",
    zh: "绿色",
    es: "Verde",
    example_ko: "나뭇잎이 초록색이에요.",
    example_en: "Leaves are green.",
    example_ja: "木の葉が緑色です。",
    example_zh: "树叶是绿色的。",
    example_es: "Las hojas son verdes."
  },
  {
    id: 160,
    category: "Colors",
    korean: "검은색",
    romanization: "geomeunsaek",
    en: "Black",
    ja: "黒",
    zh: "黑色",
    es: "Negro",
    example_ko: "제 머리는 검은색이에요.",
    example_en: "My hair is black.",
    example_ja: "私の髪は黒いです。",
    example_zh: "我的头发是黑色的。",
    example_es: "Mi pelo es negro."
  },
  {
    id: 161,
    category: "Numbers",
    korean: "하나",
    romanization: "hana",
    en: "One",
    ja: "一つ",
    zh: "一",
    es: "Uno",
    example_ko: "사과 하나 주세요.",
    example_en: "Give me one apple.",
    example_ja: "りんごを一つください。",
    example_zh: "请给我一个苹果。",
    example_es: "Dame una manzana."
  },
  {
    id: 162,
    category: "Numbers",
    korean: "둘",
    romanization: "dul",
    en: "Two",
    ja: "二つ",
    zh: "二",
    es: "Dos",
    example_ko: "사과 둘 주세요.",
    example_en: "Give me two apples.",
    example_ja: "りんごを二つください。",
    example_zh: "请给我两个苹果。",
    example_es: "Dame dos manzanas."
  },
  {
    id: 163,
    category: "Numbers",
    korean: "셋",
    romanization: "set",
    en: "Three",
    ja: "三つ",
    zh: "三",
    es: "Tres",
    example_ko: "사과 셋 주세요.",
    example_en: "Give me three apples.",
    example_ja: "りんごを三つください。",
    example_zh: "请给我三个苹果。",
    example_es: "Dame tres manzanas."
  },
  {
    id: 164,
    category: "Numbers",
    korean: "백",
    romanization: "baek",
    en: "Hundred",
    ja: "百",
    zh: "百",
    es: "Cien",
    example_ko: "백 원만 주세요.",
    example_en: "Give me a hundred won.",
    example_ja: "百ウォンだけください。",
    example_zh: "请给我一百韩元。",
    example_es: "Dame cien wones."
  },
  {
    id: 165,
    category: "Numbers",
    korean: "천",
    romanization: "cheon",
    en: "Thousand",
    ja: "千",
    zh: "千",
    es: "Mil",
    example_ko: "이거 천 원이에요.",
    example_en: "This is a thousand won.",
    example_ja: "これは千ウォンです。",
    example_zh: "这个一千韩元。",
    example_es: "Esto cuesta mil wones."
  },
  {
    id: 166,
    category: "Time",
    korean: "아침",
    romanization: "achim",
    en: "Morning",
    ja: "朝",
    zh: "早上",
    es: "Mañana",
    example_ko: "아침에 운동을 해요.",
    example_en: "I exercise in the morning.",
    example_ja: "朝に運動をします。",
    example_zh: "早上运动。",
    example_es: "Hago ejercicio por la mañana."
  },
  {
    id: 167,
    category: "Time",
    korean: "점심",
    romanization: "jeomsim",
    en: "Lunch / Noon",
    ja: "昼 / 昼食",
    zh: "中午 / 午饭",
    es: "Almuerzo / Mediodía",
    example_ko: "점심으로 라면을 먹었어요.",
    example_en: "I ate ramen for lunch.",
    example_ja: "昼食にラーメンを食べました。",
    example_zh: "午饭吃了拉面。",
    example_es: "Comí ramen para el almuerzo."
  },
  {
    id: 168,
    category: "Time",
    korean: "저녁",
    romanization: "jeonyeok",
    en: "Evening / Dinner",
    ja: "夕方 / 夕食",
    zh: "晚上 / 晚饭",
    es: "Tarde / Cena",
    example_ko: "저녁에 만나요.",
    example_en: "Let's meet in the evening.",
    example_ja: "夕方に会いましょう。",
    example_zh: "晚上见。",
    example_es: "Nos vemos por la tarde."
  },
  {
    id: 169,
    category: "Time",
    korean: "밤",
    romanization: "bam",
    en: "Night",
    ja: "夜",
    zh: "夜",
    es: "Noche",
    example_ko: "밤에는 조용해요.",
    example_en: "It is quiet at night.",
    example_ja: "夜は静かです。",
    example_zh: "晚上很安静。",
    example_es: "Por la noche está tranquilo."
  },
  {
    id: 170,
    category: "Time",
    korean: "새벽",
    romanization: "saebyeok",
    en: "Dawn",
    ja: "夜明け",
    zh: "凌晨",
    es: "Madrugada",
    example_ko: "새벽에 공부를 해요.",
    example_en: "I study at dawn.",
    example_ja: "夜明けに勉強をします。",
    example_zh: "凌晨学习。",
    example_es: "Estudio de madrugada."
  },
  {
    id: 171,
    category: "Seasons",
    korean: "봄",
    romanization: "bom",
    en: "Spring",
    ja: "春",
    zh: "春",
    es: "Primavera",
    example_ko: "봄에는 꽃이 피어요.",
    example_en: "Flowers bloom in spring.",
    example_ja: "春には花が咲きます。",
    example_zh: "春天花开。",
    example_es: "En primavera florecen las flores."
  },
  {
    id: 172,
    category: "Seasons",
    korean: "여름",
    romanization: "yeoreum",
    en: "Summer",
    ja: "夏",
    zh: "夏",
    es: "Verano",
    example_ko: "여름에는 바다에 가요.",
    example_en: "I go to the sea in summer.",
    example_ja: "夏には海に行きます。",
    example_zh: "夏天去海边。",
    example_es: "En verano voy al mar."
  },
  {
    id: 173,
    category: "Seasons",
    korean: "가을",
    romanization: "gaeul",
    en: "Autumn / Fall",
    ja: "秋",
    zh: "秋",
    es: "Otoño",
    example_ko: "가을에는 단풍이 예뻐요.",
    example_en: "The autumn leaves are pretty.",
    example_ja: "秋には紅葉が綺麗です。",
    example_zh: "秋天红叶很漂亮。",
    example_es: "En otoño el follaje es bonito."
  },
  {
    id: 174,
    category: "Seasons",
    korean: "겨울",
    romanization: "gyeoul",
    en: "Winter",
    ja: "冬",
    zh: "冬",
    es: "Invierno",
    example_ko: "겨울에는 눈이 와요.",
    example_en: "It snows in winter.",
    example_ja: "冬には雪が降ります。",
    example_zh: "冬天会下雪。",
    example_es: "En invierno nieva."
  },
  {
    id: 175,
    category: "Animals",
    korean: "개",
    romanization: "gae",
    en: "Dog",
    ja: "犬",
    zh: "狗",
    es: "Perro",
    example_ko: "개가 짖어요.",
    example_en: "The dog is barking.",
    example_ja: "犬が吠えています。",
    example_zh: "狗在叫。",
    example_es: "El perro está ladrando."
  },
  {
    id: 176,
    category: "Animals",
    korean: "고양이",
    romanization: "goyangi",
    en: "Cat",
    ja: "猫",
    zh: "猫",
    es: "Gato",
    example_ko: "고양이가 자고 있어요.",
    example_en: "The cat is sleeping.",
    example_ja: "猫が寝ています。",
    example_zh: "猫在睡觉。",
    example_es: "El gato está durmiendo."
  },
  {
    id: 177,
    category: "Animals",
    korean: "새",
    romanization: "sae",
    en: "Bird",
    ja: "鳥",
    zh: "鸟",
    es: "Pájaro",
    example_ko: "새가 하늘을 날아요.",
    example_en: "A bird is flying in the sky.",
    example_ja: "鳥が空を飛んでいます。",
    example_zh: "鸟在天空中飞。",
    example_es: "Un pájaro vuela en el cielo."
  },
  {
    id: 178,
    category: "Animals",
    korean: "물고기",
    romanization: "mulgogi",
    en: "Fish",
    ja: "魚",
    zh: "鱼",
    es: "Pez / Pescado",
    example_ko: "물고기가 헤엄을 쳐요.",
    example_en: "The fish is swimming.",
    example_ja: "魚が泳いでいます。",
    example_zh: "鱼在游泳。",
    example_es: "El pez está nadando."
  },
  {
    id: 179,
    category: "Animals",
    korean: "토끼",
    romanization: "tokki",
    en: "Rabbit",
    ja: "うさぎ",
    zh: "兔子",
    es: "Conejo",
    example_ko: "토끼가 당근을 먹어요.",
    example_en: "The rabbit eats a carrot.",
    example_ja: "うさぎが人参を食べています。",
    example_zh: "兔子吃胡萝卜。",
    example_es: "El conejo come una zanahoria."
  },
  {
    id: 180,
    category: "Places",
    korean: "공원",
    romanization: "gong-won",
    en: "Park",
    ja: "公園",
    zh: "公园",
    es: "Parque",
    example_ko: "공원에서 운동해요.",
    example_en: "I exercise in the park.",
    example_ja: "公園で運動します。",
    example_zh: "在公园里运动。",
    example_es: "Hago ejercicio en el parque."
  },
  {
    id: 181,
    category: "Places",
    korean: "도서관",
    romanization: "doseogwan",
    en: "Library",
    ja: "図書館",
    zh: "图书馆",
    es: "Biblioteca",
    example_ko: "도서관에서 책을 빌렸어요.",
    example_en: "I borrowed a book from the library.",
    example_ja: "図書館で本を借りました。",
    example_zh: "在图书馆借了书。",
    example_es: "Tomé prestado un libro de la biblioteca."
  },
  {
    id: 182,
    category: "Places",
    korean: "약국",
    romanization: "yakguk",
    en: "Pharmacy",
    ja: "薬局",
    zh: "药店",
    es: "Farmacia",
    example_ko: "약국에서 약을 샀어요.",
    example_en: "I bought medicine at the pharmacy.",
    example_ja: "薬局で薬を買いました。",
    example_zh: "在药店买了药。",
    example_es: "Compré medicina en la farmacia."
  },
  {
    id: 183,
    category: "Places",
    korean: "시장",
    romanization: "sijang",
    en: "Market",
    ja: "市場",
    zh: "市场",
    es: "Mercado",
    example_ko: "시장에서 과일을 샀어요.",
    example_en: "I bought fruit at the market.",
    example_ja: "市場で果物を買いました。",
    example_zh: "在市场买了水果。",
    example_es: "Compré fruta en el mercado."
  },
  {
    id: 184,
    category: "Places",
    korean: "영화관",
    romanization: "yeonghwagwan",
    en: "Movie theater",
    ja: "映画館",
    zh: "电影院",
    es: "Cine",
    example_ko: "영화관에서 영화를 봐요.",
    example_en: "I watch a movie at the theater.",
    example_ja: "映画館で映画を見ます。",
    example_zh: "在电影院看电影。",
    example_es: "Veo una película en el cine."
  },
  {
    id: 185,
    category: "Objects",
    korean: "책상",
    romanization: "chaeksang",
    en: "Desk",
    ja: "机",
    zh: "书桌",
    es: "Escritorio",
    example_ko: "책상 위에 연필이 있어요.",
    example_en: "There is a pencil on the desk.",
    example_ja: "机の上に鉛筆があります。",
    example_zh: "桌子上有铅笔。",
    example_es: "Hay un lápiz en el escritorio."
  },
  {
    id: 186,
    category: "Objects",
    korean: "의자",
    romanization: "uija",
    en: "Chair",
    ja: "椅子",
    zh: "椅子",
    es: "Silla",
    example_ko: "의자에 앉으세요.",
    example_en: "Please sit on the chair.",
    example_ja: "椅子に座ってください。",
    example_zh: "请坐在椅子上。",
    example_es: "Por favor, siéntate en la silla."
  },
  {
    id: 187,
    category: "Objects",
    korean: "침대",
    romanization: "chimdae",
    en: "Bed",
    ja: "ベッド",
    zh: "床",
    es: "Cama",
    example_ko: "침대가 아주 편해요.",
    example_en: "The bed is very comfortable.",
    example_ja: "ベッドがとても快適です。",
    example_zh: "床很舒服。",
    example_es: "La cama es muy cómoda."
  },
  {
    id: 188,
    category: "Objects",
    korean: "문",
    romanization: "mun",
    en: "Door",
    ja: "ドア / 門",
    zh: "门",
    es: "Puerta",
    example_ko: "문을 닫아 주세요.",
    example_en: "Please close the door.",
    example_ja: "ドアを閉めてください。",
    example_zh: "请关门。",
    example_es: "Por favor, cierra la puerta."
  },
  {
    id: 189,
    category: "Objects",
    korean: "창문",
    romanization: "changmun",
    en: "Window",
    ja: "窓",
    zh: "窗户",
    es: "Ventana",
    example_ko: "창문을 열어요.",
    example_en: "Open the window.",
    example_ja: "窓を開けます。",
    example_zh: "开窗户。",
    example_es: "Abre la ventana."
  },
  {
    id: 190,
    category: "Shopping",
    korean: "가게",
    romanization: "gage",
    en: "Shop / Store",
    ja: "店",
    zh: "店",
    es: "Tienda",
    example_ko: "가게에 손님이 많아요.",
    example_en: "There are many customers in the shop.",
    example_ja: "店にお客さんがたくさんいます。",
    example_zh: "店里有很多客人。",
    example_es: "Hay muchos clientes en la tienda."
  },
  {
    id: 191,
    category: "Shopping",
    korean: "비싸다",
    romanization: "bissada",
    en: "Expensive",
    ja: "高い",
    zh: "贵",
    es: "Caro",
    example_ko: "이거 너무 비싸요.",
    example_en: "This is too expensive.",
    example_ja: "これ、高すぎます。",
    example_zh: "这个太贵了。",
    example_es: "Esto es demasiado caro."
  },
  {
    id: 192,
    category: "Shopping",
    korean: "싸다",
    romanization: "ssada",
    en: "Cheap",
    ja: "安い",
    zh: "便宜",
    es: "Barato",
    example_ko: "물건이 아주 싸요.",
    example_en: "The items are very cheap.",
    example_ja: "品物がとても安いです。",
    example_zh: "东西很便宜。",
    example_es: "Los artículos son muy baratos."
  },
  {
    id: 193,
    category: "Shopping",
    korean: "거스름돈",
    romanization: "geoseureumdon",
    en: "Change (money)",
    ja: "お釣り",
    zh: "找零",
    es: "Cambio (dinero)",
    example_ko: "거스름돈 여기 있습니다.",
    example_en: "Here is your change.",
    example_ja: "お釣りはこちらです。",
    example_zh: "这是找你的零钱。",
    example_es: "Aquí tiene su cambio."
  },
  {
    id: 194,
    category: "Shopping",
    korean: "영수증",
    romanization: "yeongsujeung",
    en: "Receipt",
    ja: "領収書 / レシート",
    zh: "收据 / 发票",
    es: "Recibo",
    example_ko: "영수증 드릴까요?",
    example_en: "Would you like a receipt?",
    example_ja: "領収書を差し上げましょうか？",
    example_zh: "要发票吗？",
    example_es: "¿Desea un recibo?"
  },
  {
    id: 195,
    category: "Emotions",
    korean: "화나다",
    romanization: "hwanada",
    en: "To be angry",
    ja: "怒る",
    zh: "生气",
    es: "Estar enfadado",
    example_ko: "왜 그렇게 화가 났어요?",
    example_en: "Why are you so angry?",
    example_ja: "なぜそんなに怒っているのですか？",
    example_zh: "你为什么那么生气？",
    example_es: "¿Por qué estás tan enfadado?"
  },
  {
    id: 196,
    category: "Emotions",
    korean: "놀라다",
    romanization: "nollada",
    en: "To be surprised",
    ja: "驚く",
    zh: "惊讶",
    es: "Estar sorprendido",
    example_ko: "너무 놀랐어요.",
    example_en: "I was so surprised.",
    example_ja: "とても驚きました。",
    example_zh: "吓了我一跳。",
    example_es: "Estaba muy sorprendido."
  },
  {
    id: 197,
    category: "Emotions",
    korean: "무섭다",
    romanization: "museopda",
    en: "To be scared / scary",
    ja: "怖い",
    zh: "害怕",
    es: "Tener miedo / Ser miedoso",
    example_ko: "밤길이 무서워요.",
    example_en: "The night road is scary.",
    example_ja: "夜道が怖いです。",
    example_zh: "走夜路很害怕。",
    example_es: "El camino de noche da miedo."
  },
  {
    id: 198,
    category: "Emotions",
    korean: "외롭다",
    romanization: "oeropda",
    en: "To be lonely",
    ja: "寂しい",
    zh: "寂寞",
    es: "Sentirse solo",
    example_ko: "혼자 있으면 외로워요.",
    example_en: "I feel lonely when I'm alone.",
    example_ja: "一人でいると寂しいです。",
    example_zh: "一个人待着很寂寞。",
    example_es: "Me siento solo cuando estoy solo."
  },
  {
    id: 199,
    category: "Emotions",
    korean: "부끄럽다",
    romanization: "bukkeureopda",
    en: "To be shy / embarrassed",
    ja: "恥ずかしい",
    zh: "害羞",
    es: "Estar avergonzado / Ser tímido",
    example_ko: "사람들 앞에서 부끄러워요.",
    example_en: "I'm shy in front of people.",
    example_ja: "人前で恥ずかしいです。",
    example_zh: "在众人面前很害羞。",
    example_es: "Me da vergüenza delante de la gente."
  },
  {
    id: 200,
    category: "Greetings",
    korean: "안녕히 계세요",
    romanization: "annyeonghi gyeseyo",
    en: "Goodbye (to person staying)",
    ja: "さようなら",
    zh: "再见",
    es: "Adiós (al que se queda)",
    example_ko: "먼저 갈게요. 안녕히 계세요.",
    example_en: "I'll be going first. Goodbye.",
    example_ja: "お先に失礼します。さようなら。",
    example_zh: "我先走了。再见。",
    example_es: "Me voy primero. Adiós."
  }
];
